// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Net5.AspNet.MVC.Infrastructure.Data.Entities;

namespace Net5.AspNet.MVC.Infrastructure.Data.Contexts
{
    public static class BlogContextProceduresExtensions
    {
        public static BlogContextProcedures GetProcedures(this BlogContext context)
        {
            return new BlogContextProcedures(context);
        }
    }

    public partial class BlogContextProcedures
    {
        private readonly BlogContext _context;

        public BlogContextProcedures(BlogContext context)
        {
            _context = context;
        }

        public async Task<uspListPostResult[]> uspListPostAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<uspListPostResult>("EXEC @returnValue = [Blog].[uspListPost]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
