// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.MVC.Infrastructure.Data.Blog.Entities
{
    public partial class Post
    {
        public Post()
        {
            Comentarios = new HashSet<Comentario>();
        }

        public int PostId { get; set; }
        public string Titulo { get; set; }
        public string Resumen { get; set; }
        public string Contenido { get; set; }
        public string UsuarioIdPropietario { get; set; }
        public string UsuarioIdCreacion { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string UsuarioIdActualizacion { get; set; }
        public DateTime FechaActualizacion { get; set; }

        public virtual User UsuarioIdActualizacionNavigation { get; set; }
        public virtual User UsuarioIdCreacionNavigation { get; set; }
        public virtual User UsuarioIdPropietarioNavigation { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
    }
}