// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net5.Fundamentals.EF.CodeFirst.Data.Context;

namespace Net5.Fundamentals.EF.CodeFirst.Migrations
{
    [DbContext(typeof(Net5FundamentalsEFDatabaseContext))]
    partial class Net5FundamentalsEFDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdActualizacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdCreacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdPropietario")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioIdActualizacion");

                    b.HasIndex("UsuarioIdCreacion");

                    b.HasIndex("UsuarioIdPropietario");

                    b.ToTable("Comentario", "Blog");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UsuarioIdActualizacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdCreacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdPropietario")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("UsuarioIdActualizacion");

                    b.HasIndex("UsuarioIdCreacion");

                    b.HasIndex("UsuarioIdPropietario");

                    b.ToTable("Post", "Blog");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", "Blog");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Comentario", b =>
                {
                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_ComentarioPost")
                        .IsRequired();

                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdActualizacionNavigation")
                        .WithMany("ComentarioUsuarioIdActualizacionNavigations")
                        .HasForeignKey("UsuarioIdActualizacion")
                        .HasConstraintName("FK_ComentarioUsuarioActualizacion")
                        .IsRequired();

                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdCreacionNavigation")
                        .WithMany("ComentarioUsuarioIdCreacionNavigations")
                        .HasForeignKey("UsuarioIdCreacion")
                        .HasConstraintName("FK_ComentarioUsuarioCreacion")
                        .IsRequired();

                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdPropietarioNavigation")
                        .WithMany("ComentarioUsuarioIdPropietarioNavigations")
                        .HasForeignKey("UsuarioIdPropietario")
                        .HasConstraintName("FK_ComentarioUsuarioPropietario")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UsuarioIdActualizacionNavigation");

                    b.Navigation("UsuarioIdCreacionNavigation");

                    b.Navigation("UsuarioIdPropietarioNavigation");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Post", b =>
                {
                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdActualizacionNavigation")
                        .WithMany("PostUsuarioIdActualizacionNavigations")
                        .HasForeignKey("UsuarioIdActualizacion")
                        .HasConstraintName("FK_PostUsuarioActualizacion")
                        .IsRequired();

                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdCreacionNavigation")
                        .WithMany("PostUsuarioIdCreacionNavigations")
                        .HasForeignKey("UsuarioIdCreacion")
                        .HasConstraintName("FK_PostUsuarioCreacion")
                        .IsRequired();

                    b.HasOne("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", "UsuarioIdPropietarioNavigation")
                        .WithMany("PostUsuarioIdPropietarioNavigations")
                        .HasForeignKey("UsuarioIdPropietario")
                        .HasConstraintName("FK_PostUsuarioPropietario")
                        .IsRequired();

                    b.Navigation("UsuarioIdActualizacionNavigation");

                    b.Navigation("UsuarioIdCreacionNavigation");

                    b.Navigation("UsuarioIdPropietarioNavigation");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Post", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("Net5.Fundamentals.EF.CodeFirst.Data.Entities.Usuario", b =>
                {
                    b.Navigation("ComentarioUsuarioIdActualizacionNavigations");

                    b.Navigation("ComentarioUsuarioIdCreacionNavigations");

                    b.Navigation("ComentarioUsuarioIdPropietarioNavigations");

                    b.Navigation("PostUsuarioIdActualizacionNavigations");

                    b.Navigation("PostUsuarioIdCreacionNavigations");

                    b.Navigation("PostUsuarioIdPropietarioNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
