// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Net5.AspNet.MVC.Infrastructure.Data.Entities
{
    public partial class uspListPostResult
    {
        public int PostId { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public string UsuarioIdPropietario { get; set; }
        public string UsuarioIdCreacion { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string UsuarioIdActualizacion { get; set; }
        public DateTime FechaActualizacion { get; set; }
    }
}
